CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);
ALTER TABLE tasks DROP COLUMN author;
ALTER TABLE tasks ADD COLUMN user_id INT;

ALTER TABLE tasks ADD CONSTRAINT fk_tasks_user
FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;